### ISSUE TITLE
26 column limit?

### ISSUE THREAD

**Issue by samphilipd** [Voronchuk/elixir_google_spreadsheets#10]
Hi, we're looking for a library to write to a google sheet. We need to write considerably more than 26 columns, I wonder if this limitation is something that's fairly easy to remove?

**Comment by Voronchuk** [comment]
Personally, never need more then 26, but it's relatively easy to fix, you need to rewrite:
https://github.com/Voronchuk/elixir_google_spreadsheets/blob/master/lib/elixir_google_spreadsheets/spreadsheet.ex#L508
To support double letter columns like AA, AB, AC etc in a same way as Google Spreadsheets put them. Otherwise I don't see restrictions, just put optional `column_to` params as much as you need.

PR is welcome.

**Comment by Voronchuk** [comment]
Actually I see that it's supported already, but I never tested it, feel free to try and tell your results, current limit is 255 columns

**Comment by Voronchuk** [comment]
@samphilipd is it working fine, can I close this?

**Comment by samphilipd** [comment]
@Voronchuk Haven't had a chance to test yet, will let you know very soon!
